AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:

  TagKeyParam:
    Type: String
    Description: Cost allocation tag to breakup report by

  AthenaDBParam:
    Type: String
    Description: Athena database with CUR

  AthenaTableParam:
    Type: String
    Description: Athena table with CUR

  OutputBucketParam:
    Type: String
    Description: S3 bucket to use for reports generated

Resources:

  GetTagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.get_tags
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam
          OUTPUT_BUCKET: !Ref OutputBucketParam

  QueryAthenaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.query_athena
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam

  CopyFinalCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.copy_final_csv
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam
