AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:

  TagKeyParam:
    Type: String
    Description: Cost allocation tag to breakup report by

  OutputBucketParam:
    Type: String
    Description: S3 bucket to use for reports generated (must not exist already)

  AthenaDBParam:
    Type: String
    Default: aws_billing_report
    Description: Athena database with CUR

  AthenaTableParam:
    Type: String
    Default: my_cur_report
    Description: Athena table with CUR

Resources:

  GetTagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.get_tags
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam
          OUTPUT_BUCKET: !Ref OutputBucketParam

  QueryAthenaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.query_athena
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam

  CopyFinalCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.copy_final_csv
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          TAG_KEY: !Ref TagKeyParam
          ATHENA_DB: !Ref AthenaDBParam
          ATHENA_TABLE: !Ref AthenaTableParam

  QueryAthenaS3Permission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt QueryAthenaFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub arn:aws:s3:::${OutputBucketParam}

  CopyFinalCSVPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt CopyFinalCSVFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub arn:aws:s3:::${OutputBucketParam}

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketParam
      NotificationConfiguration:
        LambdaConfigurations:
          - Function: !GetAtt QueryAthenaFunction.Arn
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: tags/
                  - Name: suffix
                    Value: .csv
          - Function: !GetAtt CopyFinalCSVFunction.Arn
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: athena_out/
                  - Name: suffix
                    Value: .csv
    DependsOn:
      - QueryAthenaS3Permission
      - CopyFinalCSVPermission

Outputs:
  GetTagsFunctionArn:
    Value: !GetAtt GetTagsFunction.Arn
    Description: Lambda function to by triggered by Athena CUR bucket
  ReportBucket:
    Value: !Ref OutputBucketParam
    Description: Bucket reports are being saved to
